baseURL = "https://nasan92.github.io"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Nasan"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "Youtube"
    pre = ""
    post = ""
    name = "Youtube"
    url = "https://www.youtube.com/channel/UCD152s9TkCpwTFTTXzdjvCw"
    title = ""
    weight = 4
#  [[menu.main]]
#     identifier = "MindMaps"
#     pre = ""
#     post = ""
#     name = "MindMaps"
#     url = "/MindMaps/"
#     title = ""
#     weight = 5
#  [[menu.main]]
#     identifier = "MindMaps2"
#     pre = ""
#     post = ""
#     name = "MindMaps2"
#     url = "/mindmaps/mindmap2/"
#     title = ""
#     weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
