baseURL = "https://nasan92.github.io"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "NASAN"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

 # LoveIt NEW | 0.2.0 Search config
[params.search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # LoveIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # LoveIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""


# Footer config
[params.footer]
  enable = true
  # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
  custom = 'Nathanael Santschi Blog'
  # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
  hugo = true
  # LoveIt NEW | 0.2.0 whether to show copyright info
  copyright = true
  # LoveIt NEW | 0.2.0 whether to show the author
  author = true
  # Site creation time
  since = 2022
  # ICP info only in China (HTML format is supported)
  icp = ""
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


# Home page config
[params.home]
  # LoveIt NEW | 0.2.0 amount of RSS pages
  rss = 10
  # Home page profile
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/nasan-avatar.jpeg"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page
    subtitle = "Welcome to my Blog, maybe you will find something helpful"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6
    # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
    # default behavior when you don't set "hiddenFromHomePage" in front matter
    defaultHiddenFromHomePage = false

 # Social config about the author
  [params.social]
    GitHub = "nasan92"
    # Linkedin = ""
    Twitter = "@nasantschi"
    # Instagram = "xxxx"
    # Facebook = "xxxx"
    # Telegram = "xxxx"
    # Medium = ""
    # Gitlab = ""
    # Youtubelegacy = ""
    # Youtubecustom = ""
    # Youtubechannel = ""
    # Tumblr = ""
    # Quora = ""
    # Keybase = ""
    # Pinterest = ""
    # Reddit = ""
    # Codepen = ""
    # FreeCodeCamp = ""
    # Bitbucket = ""
    # Stackoverflow = ""
    # Weibo = ""
    # Odnoklassniki = ""
    # VK = ""
    # Flickr = ""
    # Xing = ""
    # Snapchat = ""
    # Soundcloud = ""
    # Spotify = ""
    # Bandcamp = ""
    # Paypal = ""
    # Fivehundredpx = ""
    # Mix = ""
    # Goodreads = ""
    # Lastfm = ""
    # Foursquare = ""
    # Hackernews = ""
    # Kickstarter = ""
    # Patreon = ""
    # Steam = ""
    # Twitch = ""
    # Strava = ""
    # Skype = ""
    # Whatsapp = ""
    # Zhihu = ""
    # Douban = ""
    # Angellist = ""
    # Slidershare = ""
    # Jsfiddle = ""
    # Deviantart = ""
    # Behance = ""
    # Dribbble = ""
    # Wordpress = ""
    # Vine = ""
    # Googlescholar = ""
    # Researchgate = ""
    # Mastodon = ""
    # Thingiverse = ""
    # Devto = ""
    # Gitea = ""
    # XMPP = ""
    # Matrix = ""
    # Bilibili = ""
    # Email = "xxxx@xxxx.com"
    # RSS = true # LoveIt NEW | 0.2.0


[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "Youtube"
    pre = ""
    post = ""
    name = "Youtube"
    url = "https://www.youtube.com/channel/UCD152s9TkCpwTFTTXzdjvCw"
    title = ""
    weight = 4
#  [[menu.main]]
#     identifier = "MindMaps"
#     pre = ""
#     post = ""
#     name = "MindMaps"
#     url = "/MindMaps/"
#     title = ""
#     weight = 5
#  [[menu.main]]
#     identifier = "MindMaps2"
#     pre = ""
#     post = ""
#     name = "MindMaps2"
#     url = "/mindmaps/mindmap2/"
#     title = ""
#     weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
